name: 'Add issue/PR to Triage Board'
on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
jobs:
  add-to-triage-project-board:
    uses: nagash77/github-actions/.github/workflows/main.yml@main
    secrets: inherit
