name: 'Add issue/PR to Triage Board'
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
    
jobs:
  add-to-triage-project-board:
    if: >-
      (
        contains(github.event.pull_request.labels.*.name, 'stale') ||
        contains(github.event.issue.labels.*.name, 'stale')
      )
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo 'I ran!'
