name: 'Add stale issue/PR to Triage Board'
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add-to-triage-project-board:
    if: >-
      (
        contains(github.event.pull_request.labels.*.name, 'stale') ||
        contains(github.event.issue.labels.*.name, 'stale')
      )
    uses: nagash77/github-actions/.github/workflows/add_to_triage_board.yml@main
    secrets: inherit
  update-status-to-awaiting-response:
    needs: add-to-triage-project-board
    uses: nagash77/github-actions/.github/workflows/triage_update_status.yml@main
    with:
      status: 'Awaiting Response'
    secrets: inherit
