name: 'Add stale issue/PR to Triage Board'
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add-to-triage-project-board:
    runs-on: ubuntu-latest
    steps:
    - uses: nagash77/github-actions/.github/workflows/add_to_triage_board.yml@develop
      with:
        secrets: ${{ secrets }}
    - uses: nagash77/github-actions/triage_update_status.yml@develop
      with:
        status: 'Awaiting Response'
        secrets: ${{ secrets }}
