name: 'Move stale issue to Awaiting Response'
on:
  issues:
    types: [labeled]
  
jobs:
  add-to-triage-project-board:
    if: >-
      (
        contains(github.event.pull_request.labels.*.name, 'stale') ||
        contains(github.event.issue.labels.*.name, 'stale')
      )
    uses: nagash77/github-actions/.github/workflows/triage_update_status.yml@main
    with:
      status: 'Awaiting Response'
    secrets: inherit
