name: 'Add stale issue/PR to Triage Board'
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add-to-triage-project-board:
    if: ( contains(github.event.pull_request.labels.*.name, 'stale') || contains(github.event.issue.labels.*.name, 'stale') )
    steps:
      - uses: nagash77/github-actions/.github/workflows/add_to_triage_board.yml@develop
        with:
          secrets: ${{ secrets }}
      - uses: nagash77/github-actions/triage_update_status.yml@develop
        with:
          status: 'Awaiting Response'
          secrets: ${{ secrets }}
